#!/bin/sh
# First-boot config seed for the OpenCode container (run once per fresh
# opencode-config volume, before the server starts).
#
# Writes opencode.json with a LOCAL Backlog MCP (`backlog mcp start`) pointed
# at the same authoritative BACKLOG_CWD the ledger service mounts (/data).
# One resource, no phantom isolated ledger.
#
# Safety properties (F10):
#   - JSON is generated by node's JSON.stringify (the image ships node), so
#     a hostile BACKLOG_SEED_CWD string can never escape the string literal
#     or inject structure into the config.
#   - Refuses to write if the config path is a symlink (would write through
#     it to a target outside the config volume).
#   - Pre-existing config is preserved (idempotent; volume reuse never
#     clobbers operator edits). Pre-existing OTHER data in the config dir is
#     never touched.
#   - BACKLOG_SEED_CWD must be an absolute path within the allowed config
#     mount roots (/data or the workspace); a relative or escaping value
#     (e.g. ".." traversal pointing outside) is refused.
#   - Exit 0 when the config already exists (nothing to do), exit non-zero
#     on any refusal/failure (fail loud, never half-write).

set -eu

CFG="$HOME/.config/opencode/opencode.json"
BACKLOG_CWD="${BACKLOG_SEED_CWD:-/data}"

if [ -L "$CFG" ]; then
  echo "FATAL: $CFG is a symlink; refusing to seed through it" >&2
  exit 1
fi

if [ -f "$CFG" ]; then
  echo "opencode.json already present; leaving it untouched"
  exit 0
fi

mkdir -p "$(dirname "$CFG")"

# node in the image validates + generates the JSON. Never shell-interpolate
# the CWD into the output.
node - "$CFG" "$BACKLOG_CWD" <<'NODE_EOF'
const fs = require("fs");
const path = require("path");

const [cfgPath, backlogCwd] = process.argv.slice(2);

// Strict input validation for the CWD string.
if (typeof backlogCwd !== "string" || backlogCwd.length === 0) {
  console.error("FATAL: BACKLOG_SEED_CWD must be a non-empty string");
  process.exit(2);
}
if (!path.isAbsolute(backlogCwd)) {
  console.error(`FATAL: BACKLOG_SEED_CWD must be absolute, got: ${backlogCwd}`);
  process.exit(2);
}
// No parent traversal or symlink-ish escapes; must be inside the allowed
// resource/config roots (/data or /workspace).
const allowedRoots = ["/data", "/workspace"];
const resolved = path.resolve(backlogCwd);
const allowed = allowedRoots.some(
  (root) => resolved === root || resolved.startsWith(root + "/")
);
if (!allowed) {
  console.error(
    `FATAL: BACKLOG_SEED_CWD must be inside one of ${allowedRoots.join(", ")}; got: ${resolved}`
  );
  process.exit(2);
}

// Refuse to write through a symlink at the final path (re-check inside node:
// the shell -f test ran earlier, but nothing else may have created a link).
let st = null;
try { st = fs.lstatSync(cfgPath); } catch {}
if (st && st.isSymbolicLink()) {
  console.error(`FATAL: ${cfgPath} is a symlink; refusing to seed through it`);
  process.exit(2);
}
if (st) {
  console.log("opencode.json already present; leaving it untouched");
  process.exit(0);
}

const config = {
  $schema: "https://opencode.ai/config.json",
  autoupdate: false,
  share: "disabled",
  mcp: {
    backlog: {
      type: "local",
      command: ["backlog", "mcp", "start"],
      enabled: true,
      environment: { BACKLOG_CWD: backlogCwd },
    },
  },
};

fs.writeFileSync(cfgPath, JSON.stringify(config, null, 2) + "\n", { flag: "wx" });
console.log(`seeded ${cfgPath} (backlog MCP at BACKLOG_CWD=${backlogCwd})`);
NODE_EOF